"""change size location Event

Revision ID: 0083650acda0
Revises: 4e03252af6b1
Create Date: 2017-01-29 21:02:20.619671

"""

# revision identifiers, used by Alembic.
revision = '0083650acda0'
down_revision = '4e03252af6b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
