"""something change

Revision ID: 2515f93285c3
Revises: ddb6fcd5d32e
Create Date: 2017-01-08 15:43:28.887877

"""

# revision identifiers, used by Alembic.
revision = '2515f93285c3'
down_revision = 'ddb6fcd5d32e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
